[package]
name = "tipis"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tipis"
path = "src/main.rs"

[dependencies]
clap = { version = "4.3.8", features = ["derive", "env"] }
lazy_static = "1.4.0"
rusqlite = "0.29.0"
thiserror = "1.0.40"

[build-dependencies]
dotenv = "0.15.0"
