[package]
name = "tic"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tic"
path = "src/main.rs"

[dependencies]
clap = { version = "4.3.8", features = ["derive", "env"] }
rusqlite = "0.29.0"
thiserror = "1.0.40"
tilog = { path = "../tilog" }

[build-dependencies]
dotenv = "0.15.0"
